/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CreateOpts {
  /** Region size in bytes (default 1 MiB). */
  size?: number
  /** Short alphanumeric token used to derive the shared-memory id. */
  id?: string
  /** Backend: "mmap" (default) or "sab". */
  backend?: string
}
export interface AttachOpts {
  /** Backend of the region to attach ("mmap"; "sab" uses wrap()). */
  backend?: string
}
export declare class SharedRegion {
  static create(opts: CreateOpts): SharedRegion
  static attach(opts: AttachOpts, id: string): SharedRegion
  static wrap(buffer: Buffer): SharedRegion
  root(): NodeRef
  createObject(capacity: number): NodeRef
  createArray(capacity: number): NodeRef
  createMap(capacity: number): NodeRef
  base(): bigint
  capacity(): bigint
  /** Shared-memory id. Pass this to worker threads so they can `attach()`. */
  id(): string
  /**
   * Detach/unlink the backing object. For the mmap backend this removes the
   * POSIX name so no further attachments can be made (existing maps stay
   * valid). Call this after all workers have attached. No-op for SAB.
   */
  close(): void
}
export declare class NodeRef {
  /** Type name: "Object" | "Array" | "Map" | scalar. */
  typeName(): string
  isObject(): boolean
  isArray(): boolean
  isMap(): boolean
  length(): number
  /** Return the container child at `key`, or null if it is a scalar/missing. */
  get_node(key: unknown): NodeRef | null
  /** Materialize the scalar at `key` (null for containers/missing). */
  get_value(key: unknown): unknown
  has(key: unknown): boolean
  set(key: unknown, value: unknown): void
  set_node(key: unknown, child: NodeRef): void
  push(value: unknown): number
  push_node(child: NodeRef): number
  increment(key: unknown): number
  delete(key: unknown): boolean
  keys(): Array<string>
}
